name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true # set CI to true in env var so test script won't run in watch mode
      MONGODB_URL: mongodb://localhost/nasa
      CLIENT_ID: MOCK_CLIENT_ID
      CLIENT_SECRET: MOCK_CLIENT_SECRET
      COOKIE_KEY_1: MOCK_KEY_1
      COOKIE_KEY_2: MOCK_KEY_2
    strategy:
      matrix:
        node-version: [14.x, 16.x] # run the steps below in both latest node 14 and 16 versions
        mongodb-version: ["4.4"]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository for following build steps
        uses: actions/checkout@v3

      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}} # ref matrix node-version above

      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{matrix.mongodb-version}} # ref matrix mongodb-version above

      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
